const aliments = {
    Boissons: {
        Cafe: 15,
        'Coca Cola': 100,
        Oasis: 68,
        Orangina: 71,
        Pepsi: 42,
        Perrier: 0,
        Eau: 0,
        "Sirop a l'eau": 33,
        The: 0,
        'The glace': 30,
        'Jus de citron': 32,
        "Jus d'Ananas": 54,
        'Jus de Pomme': 46,
        "Jus d'Orange": 45,
        'Lait concentre': 130,
        'Lait ecreme': 34,
        'Lait entier': 65,
        'Chocolat au lait': 550,
    },
    Feculents: {
        Baguette: 510,
        Biscottes: 39,
        Cracottes: 480,
        'Pain Blanc': 255,
        Biscuit: 400,
        Brioche: 386,
        Croissant: 180,
        Gauffre: 400,
        Crepes: 227,
        'Pain au chocolat': 280,
        'Barre cereales': 79,
        'Cereales nature': 378,
        'Cereales au chocolat': 401,
        'Pain perdu': 229,
    },
    Complements: {
        Beurre: 760,
        Nutella: 530,
        Miel: 304,
        Caramel: 382,
        Confiture: 278,
        Cassonnade: 380,
        Sucre: 396,
        Regilait: 360,
    },
    Fruits: {
        Abricot: 45,
        Banane: 89,
        Pomme: 52,
        Poire: 57,
        Fraise: 33,
    },
    'Produits laitiers': {
        'Fromage Blanc': 80,
        Yaourt: 120,
    },
    Autre: {
        'Oeuf dur': 70,
        'Oeuf plat': 90,
        'Oeuf poche': 143,
        Bacon: 385,
    },
};

export default aliments;
